name: Merge

on:
  push:
    branches: [main, testmergebranch]
    paths-ignore:
      - '*.md'
      - '.github/**'
      - '.github/graphics/**'
      - '!.github/workflows/**'
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag set to deploy; e.g. PR number or prod"
        type: string
        default: 'prod'

concurrency:
  # Do not interrupt previous workflows
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions: {}

jobs:
  # https://github.com/bcgov/quickstart-openshift-helpers
  deploy-dev:
    name: Deploy (DEV)
    uses: ./.github/workflows/.deployer.yml
    secrets: inherit
    with:
      environment: dev
      db_user: appproxy
      tag: ${{ inputs.tag }}
      params: --set frontend.enabled=false --set crunchy.enabled=false --set backend.migrations.enabled=false --set global.secrets.enabled=false --set global.secrets.persist=false

  tests:
    name: Tests
    needs: [deploy-dev]
    uses: ./.github/workflows/.tests.yml
    with:
      target: dev

  deploy-test:
    name: Deploy (TEST)
    needs: [tests]
    uses: ./.github/workflows/.deployer.yml
    secrets: inherit
    with:
      environment: test
      db_user: appproxy
      tag: ${{ inputs.tag }}
      params: --set frontend.enabled=false --set crunchy.enabled=false --set backend.migrations.enabled=false --set global.secrets.enabled=false --set global.secrets.persist=false

  # deploy-prod:
  #   name: Deploy (PROD)
  #   needs: [deploy-test]
  #   uses: ./.github/workflows/.deployer.yml
  #   secrets: inherit
  #   with:
  #     environment: prod
  #     db_user: appproxy
  #     params:
  #       --set backend.deploymentStrategy=RollingUpdate
  #       --set global.autoscaling=true
  #       --set backend.pdb.enabled=true
  #       --set frontend.enabled=false
  #       --set crunchy.enabled=false
  #     tag: ${{ inputs.tag }}

  # promote:
  #   name: Promote Images
  #   needs: [deploy-prod]
  #   runs-on: ubuntu-24.04
  #   permissions:
  #     packages: write
  #   strategy:
  #     matrix:
  #       package: [backend]  # Only backend for now
  #   timeout-minutes: 1
  #   steps:
  #     - uses: shrink/actions-docker-registry-tag@f04afd0559f66b288586792eb150f45136a927fa # v4
  #       with:
  #         registry: ghcr.io
  #         repository: ${{ github.repository }}-${{ matrix.package }}
  #         target: ${{ needs.deploy-prod.outputs.tag }}
  #         tags: prod
